---
name: users
route: /users
method: GET
definitions:
  - message_type: request
    versions: ["1.0"]
    schema: {}
    examples: []
  - message_type: response
    versions: ["1.0"]
    status_codes: ["2xx", "404"]
    schema:
      description: Returns a list of users
      type: object
      properties:
        users:
          description: List of users
          type: array
          items:
            type: object
            properties:
              id:
                description: The user's identifier
                type: integer
              name:
                description: The user's name
                type: string
              birthday:
                description: The user's birthday
                type: string
                format: date
    examples:
      - users:
        - id: 1
          name: John Smith
          birthday: '1970-07-21'
        - id: 2
          name: Franklin Doge
          birthday: '1985-12-18'
