default: &default
  adapter: postgresql
  encoding: utf8

development:
  <<: *default
  database: interpolate_development

test:
  <<: *default
  database: interpolate_test

production:
  <<: *default
  database: interpolate_production
